// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkvocyjsxwcvdkczkheg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdm9jeWpzeHdjdmRrY3praGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Njk0MjAsImV4cCI6MjA2ODU0NTQyMH0.wfksdftdHjV88h_CLE10zhD5G7pGGkDref6rZldfaRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});